# Base configuration for routes.yaml

imports:
  - { resource: '../vendor/derafu/content/resources/config/content-routes.yaml' }

homepage:
  path: /
  handler: '%kernel.project_dir%/templates/pages/home.html.twig'

errorpage:
  path: error
  handler: '%kernel.project_dir%/templates/error.html.twig'

contact:
  path: /contact
  handler: 'App\Controller\ContactController::index'

contact_submit:
  path: /contact/submit
  handler: 'App\Controller\ContactController::submit'

contact_success:
  path: /contact/success
  handler: 'App\Controller\ContactController::success'
